apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "simple-rest-api.fullname" . }}-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ include "simple-rest-api.fullname" . }}-postgresql:{{ .Values.postgresql.servicePort }}/{{ .Values.postgresql.postgresqlDatabase }}"
  SPRING_DATASOURCE_USERNAME: "{{ .Values.postgresql.postgresqlUsername }}"
