apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-rest-api.fullname" . }}
  labels:
    app: {{ include "simple-rest-api.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "simple-rest-api.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "simple-rest-api.name" . }}
    spec:
      containers:
      - name: backend
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "simple-rest-api.fullname" . }}-config
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: {{ include "simple-rest-api.fullname" . }}-config
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "simple-rest-api.fullname" . }}-secret
              key: spring.datasource.password
