apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "simple-rest-api.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "simple-rest-api.fullname" . }}
            port:
              number: 8080
