apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "simple-rest-api.fullname" . }}-postgresql
  labels:
    app: {{ include "simple-rest-api.name" . }}
spec:
  serviceName: {{ include "simple-rest-api.fullname" . }}-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "simple-rest-api.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "simple-rest-api.name" . }}
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: {{ .Values.postgresql.servicePort }}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.postgresqlDatabase }}
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.postgresqlUsername }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "simple-rest-api.fullname" . }}-secret
              key: spring.datasource.password
        volumeMounts:
        - name: postgredb-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgredb-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
